#!/usr/bin/env bash
# Thiết lập FE → BE local + backend .env khớp VPS (VMS test MP4, inference từ weights đã pull).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

CAM03="${ROOT}/public/camera-feeds/ttdv-a-cam03-test.mp4"
CAM04="${ROOT}/public/camera-feeds/ttdv-a-cam04-test.mp4"

cat > .env.local <<EOF
# Local dev — FE :5173 → BE :8000 (npm run start:local)
VITE_MOBILE_AI_BACKEND_URL=http://127.0.0.1:8000
VITE_VMS_BACKEND_URL=http://127.0.0.1:8000
EOF
echo "→ .env.local → http://127.0.0.1:8000"

mkdir -p backend-ai/data/auto_train
cat > backend-ai/.env <<EOF
# Local dev — khớp Contabo (VMS + inference), trừ auto-train thu mẫu (chỉ trên VPS).
HOST=0.0.0.0
PORT=8000
DETECTION_LOOP_ENABLED=false
CAMERA_SOURCE=0

AUTO_TRAIN_ENABLED=false
AUTO_TRAIN_INFERENCE_ENABLED=true
AUTO_TRAIN_SCHEDULE_HOURS_LOCAL=0,6
AUTO_TRAIN_SCHEDULE_TZ_OFFSET_HOURS=7
AUTO_TRAIN_SCHEDULE_WINDOW_MINUTES=90
AUTO_TRAIN_CHECK_INTERVAL_SECONDS=120
AUTO_TRAIN_MIN_INTERVAL_SECONDS=39600
AUTO_TRAIN_MIN_NEW_SAMPLES_DELTA=10

VMS_MODE_ENABLED=true
VMS_CAMERA_SOURCES=A-03:${CAM03},A-04:${CAM04}
VMS_AI_FPS=6.0

DETECTION_FPS=6.0
STREAM_FPS=12.0

FIRE_MODEL_REPO=SalahALHaismawi/yolov26-fire-detection
FIRE_MODEL_FILE=best.pt
FIRE_CONF_THRESHOLD=0.62
FLAME_HEURISTIC_CONF_THRESHOLD=0.48

SMOKING_MODEL_REPO=Enos-123/smoking-detection
SMOKING_MODEL_FILE=best.pt
SMOKING_CONF_THRESHOLD=0.5

EVENT_COOLDOWN_SECONDS=900.0
SMOKING_EVENT_MIN_DURATION_SECONDS=2.5
SMOKING_EVENT_MAX_GAP_SECONDS=12.0
SMOKING_EVENT_COOLDOWN_SECONDS=900.0
SMOKING_EVENT_REPEAT_MIN_SECONDS=900.0
FIRE_EVENT_MIN_DURATION_SECONDS=6.0
FIRE_EVENT_MAX_GAP_SECONDS=3.0
FIRE_EVENT_COOLDOWN_SECONDS=900.0
ROAD_EVENT_REPEAT_SECONDS=900.0
CRANE_EVENT_REPEAT_SECONDS=900.0
PPE_EVENT_REPEAT_SECONDS=900.0
PCCC_EVENT_REPEAT_SECONDS=900.0
WAH_EVENT_REPEAT_SECONDS=900.0
ATGT_EVENT_REPEAT_SECONDS=900.0
EVENT_REPEAT_MIN_SECONDS=900.0
EVENT_TEST_MODE=true
A03_BPTC_EVENT_LOGGING_ENABLED=true
EOF
echo "→ backend-ai/.env (VMS local, inference bật, auto-train thu mẫu tắt)"

echo ""
echo "✓ Local dev sẵn sàng."
echo "  1. SSH_KEY=~/.ssh/vifence_contabo ./scripts/pull-auto-train.sh  (parity weights)"
echo "  2. npm run start:local"
